[tox]
requires =
    tox>=4
    tox-uv>=1.0.0
env_list = py{310,311,312,313}

[testenv:dev]
runner = uv-venv-lock-runner
description = dev environment
extras =
    dev
    processing
commands =
    pytest {posargs}
